version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    resource_class: large
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update
            # install dependencies
            sudo apt install -y git
            # driver
            git clone --depth 1 --branch 0.3.5 https://github.com/ldbc/ldbc_snb_driver && cd ldbc_snb_driver && mvn install -DskipTests && cd ..
            # Cypher
            cd cypher
            cd ..
            # PostgreSQL
            # TODO
      - run:
          name: Prepare Cypher test data
          command: |
            cp -r cypher/test-data/raw/* cypher/test-data/converted/
      - run:
          name: Load
          command: |
            # Cypher
            cd cypher
            . scripts/environment-variables-default.sh
            scripts/load-in-one-step.sh
            cd ..
            # PostgreSQL
            # TODO
      - run:
          name: Package
          command: mvn package -DskipTests
      - run:
          name: Run Cypher project
          command: |
            cd cypher
            ./interactive-create-validation-parameters.sh
      - slack/status
