version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    resource_class: large
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update
            # install dependencies
            sudo apt install -y git
            # clone, build, and install driver
            git clone --depth 1 --branch 0.3.5 https://github.com/ldbc/ldbc_snb_driver && cd ldbc_snb_driver && mvn install -DskipTests && cd ..
            # PostgreSQL
            pip3 install --user --progress-bar off psycopg2-binary
      - run:
          name: Build project
          command: ./build.sh
      - run:
          name: Load Cypher/Neo4j database (1st time)
          command: |
            cd cypher
            . scripts/environment-variables-default.sh
            scripts/load-in-one-step.sh
            cd ..
      - run:
          name: Create validation parameters with Neo4j/Cypher project
          command: |
            cd cypher
            driver/create-validation-parameters.sh
            mv validation_params.csv validation_params_cypher.csv
            cd ..
      - run:
          name: Load PostgreSQL database (1st time)
          command: |
            cd postgres
            export POSTGRES_CSV_DIR=`pwd`/test-data/
            scripts/start.sh
            scripts/create-db.sh
            scripts/load.sh
            cd ..
      - run:
          name: Create validation parameters with the PostgreSQL project
          command: |
            cd postgres
            driver/create-validation-parameters.sh
            mv validation_params.csv validation_params_postgres.csv
            cd ..
      - run:
          name: Load Cypher/Neo4j database (2nd time)
          command: |
            cd cypher
            . scripts/environment-variables-default.sh
            scripts/load-in-one-step.sh
            cd ..
      - run:
          name: Cross-validate the Neo4j/Cypher project based on the results from Postgres
          command: |
            mv postgres/validation_params_postgres.csv cypher/validation_params.csv
            cd cypher
            driver/validate.sh | tee validation-log.txt
            grep 'Validation Result: PASS' validation-log.txt
            cd ..
      - run:
          name: Load PostgreSQL database (2nd time)
          command: |
            cd postgres
            export POSTGRES_CSV_DIR=`pwd`/test-data/
            scripts/start.sh
            scripts/create-db.sh
            scripts/load.sh
            cd ..
      - run:
          name: Cross-validate the Postgres project based on the results from Neo4j/Cypher
          command: |
            mv cypher/validation_params_cypher.csv postgres/validation_params.csv
            cd postgres
            driver/validate.sh | tee validation-log.txt
            grep 'Validation Result: PASS' validation-log.txt
            cd ..
      - slack/status
